# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/louis/github/cpp_indie_studio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/louis/github/cpp_indie_studio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/louis/github/cpp_indie_studio/CMakeFiles /home/louis/github/cpp_indie_studio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/louis/github/cpp_indie_studio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named indie_studio

# Build rule for target.
indie_studio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 indie_studio
.PHONY : indie_studio

# fast build rule for target.
indie_studio/fast:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/build
.PHONY : indie_studio/fast

src/Clock.o: src/Clock.cpp.o

.PHONY : src/Clock.o

# target to build an object file
src/Clock.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Clock.cpp.o
.PHONY : src/Clock.cpp.o

src/Clock.i: src/Clock.cpp.i

.PHONY : src/Clock.i

# target to preprocess a source file
src/Clock.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Clock.cpp.i
.PHONY : src/Clock.cpp.i

src/Clock.s: src/Clock.cpp.s

.PHONY : src/Clock.s

# target to generate assembly for a file
src/Clock.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Clock.cpp.s
.PHONY : src/Clock.cpp.s

src/Event.o: src/Event.cpp.o

.PHONY : src/Event.o

# target to build an object file
src/Event.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Event.cpp.o
.PHONY : src/Event.cpp.o

src/Event.i: src/Event.cpp.i

.PHONY : src/Event.i

# target to preprocess a source file
src/Event.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Event.cpp.i
.PHONY : src/Event.cpp.i

src/Event.s: src/Event.cpp.s

.PHONY : src/Event.s

# target to generate assembly for a file
src/Event.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Event.cpp.s
.PHONY : src/Event.cpp.s

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/GraphicalEngine.o: src/GraphicalEngine.cpp.o

.PHONY : src/GraphicalEngine.o

# target to build an object file
src/GraphicalEngine.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/GraphicalEngine.cpp.o
.PHONY : src/GraphicalEngine.cpp.o

src/GraphicalEngine.i: src/GraphicalEngine.cpp.i

.PHONY : src/GraphicalEngine.i

# target to preprocess a source file
src/GraphicalEngine.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/GraphicalEngine.cpp.i
.PHONY : src/GraphicalEngine.cpp.i

src/GraphicalEngine.s: src/GraphicalEngine.cpp.s

.PHONY : src/GraphicalEngine.s

# target to generate assembly for a file
src/GraphicalEngine.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/GraphicalEngine.cpp.s
.PHONY : src/GraphicalEngine.cpp.s

src/Human.o: src/Human.cpp.o

.PHONY : src/Human.o

# target to build an object file
src/Human.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Human.cpp.o
.PHONY : src/Human.cpp.o

src/Human.i: src/Human.cpp.i

.PHONY : src/Human.i

# target to preprocess a source file
src/Human.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Human.cpp.i
.PHONY : src/Human.cpp.i

src/Human.s: src/Human.cpp.s

.PHONY : src/Human.s

# target to generate assembly for a file
src/Human.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Human.cpp.s
.PHONY : src/Human.cpp.s

src/IAPlayer.o: src/IAPlayer.cpp.o

.PHONY : src/IAPlayer.o

# target to build an object file
src/IAPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/IAPlayer.cpp.o
.PHONY : src/IAPlayer.cpp.o

src/IAPlayer.i: src/IAPlayer.cpp.i

.PHONY : src/IAPlayer.i

# target to preprocess a source file
src/IAPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/IAPlayer.cpp.i
.PHONY : src/IAPlayer.cpp.i

src/IAPlayer.s: src/IAPlayer.cpp.s

.PHONY : src/IAPlayer.s

# target to generate assembly for a file
src/IAPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/IAPlayer.cpp.s
.PHONY : src/IAPlayer.cpp.s

src/Map.o: src/Map.cpp.o

.PHONY : src/Map.o

# target to build an object file
src/Map.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Map.cpp.o
.PHONY : src/Map.cpp.o

src/Map.i: src/Map.cpp.i

.PHONY : src/Map.i

# target to preprocess a source file
src/Map.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Map.cpp.i
.PHONY : src/Map.cpp.i

src/Map.s: src/Map.cpp.s

.PHONY : src/Map.s

# target to generate assembly for a file
src/Map.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Map.cpp.s
.PHONY : src/Map.cpp.s

src/Physics.o: src/Physics.cpp.o

.PHONY : src/Physics.o

# target to build an object file
src/Physics.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Physics.cpp.o
.PHONY : src/Physics.cpp.o

src/Physics.i: src/Physics.cpp.i

.PHONY : src/Physics.i

# target to preprocess a source file
src/Physics.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Physics.cpp.i
.PHONY : src/Physics.cpp.i

src/Physics.s: src/Physics.cpp.s

.PHONY : src/Physics.s

# target to generate assembly for a file
src/Physics.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Physics.cpp.s
.PHONY : src/Physics.cpp.s

src/SoundEngine.o: src/SoundEngine.cpp.o

.PHONY : src/SoundEngine.o

# target to build an object file
src/SoundEngine.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/SoundEngine.cpp.o
.PHONY : src/SoundEngine.cpp.o

src/SoundEngine.i: src/SoundEngine.cpp.i

.PHONY : src/SoundEngine.i

# target to preprocess a source file
src/SoundEngine.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/SoundEngine.cpp.i
.PHONY : src/SoundEngine.cpp.i

src/SoundEngine.s: src/SoundEngine.cpp.s

.PHONY : src/SoundEngine.s

# target to generate assembly for a file
src/SoundEngine.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/SoundEngine.cpp.s
.PHONY : src/SoundEngine.cpp.s

src/Weapons/AWeapon.o: src/Weapons/AWeapon.cpp.o

.PHONY : src/Weapons/AWeapon.o

# target to build an object file
src/Weapons/AWeapon.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Weapons/AWeapon.cpp.o
.PHONY : src/Weapons/AWeapon.cpp.o

src/Weapons/AWeapon.i: src/Weapons/AWeapon.cpp.i

.PHONY : src/Weapons/AWeapon.i

# target to preprocess a source file
src/Weapons/AWeapon.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Weapons/AWeapon.cpp.i
.PHONY : src/Weapons/AWeapon.cpp.i

src/Weapons/AWeapon.s: src/Weapons/AWeapon.cpp.s

.PHONY : src/Weapons/AWeapon.s

# target to generate assembly for a file
src/Weapons/AWeapon.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Weapons/AWeapon.cpp.s
.PHONY : src/Weapons/AWeapon.cpp.s

src/Weapons/Gun.o: src/Weapons/Gun.cpp.o

.PHONY : src/Weapons/Gun.o

# target to build an object file
src/Weapons/Gun.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Weapons/Gun.cpp.o
.PHONY : src/Weapons/Gun.cpp.o

src/Weapons/Gun.i: src/Weapons/Gun.cpp.i

.PHONY : src/Weapons/Gun.i

# target to preprocess a source file
src/Weapons/Gun.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Weapons/Gun.cpp.i
.PHONY : src/Weapons/Gun.cpp.i

src/Weapons/Gun.s: src/Weapons/Gun.cpp.s

.PHONY : src/Weapons/Gun.s

# target to generate assembly for a file
src/Weapons/Gun.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Weapons/Gun.cpp.s
.PHONY : src/Weapons/Gun.cpp.s

src/Weapons/Kamikaze.o: src/Weapons/Kamikaze.cpp.o

.PHONY : src/Weapons/Kamikaze.o

# target to build an object file
src/Weapons/Kamikaze.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Weapons/Kamikaze.cpp.o
.PHONY : src/Weapons/Kamikaze.cpp.o

src/Weapons/Kamikaze.i: src/Weapons/Kamikaze.cpp.i

.PHONY : src/Weapons/Kamikaze.i

# target to preprocess a source file
src/Weapons/Kamikaze.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Weapons/Kamikaze.cpp.i
.PHONY : src/Weapons/Kamikaze.cpp.i

src/Weapons/Kamikaze.s: src/Weapons/Kamikaze.cpp.s

.PHONY : src/Weapons/Kamikaze.s

# target to generate assembly for a file
src/Weapons/Kamikaze.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Weapons/Kamikaze.cpp.s
.PHONY : src/Weapons/Kamikaze.cpp.s

src/Weapons/Knife.o: src/Weapons/Knife.cpp.o

.PHONY : src/Weapons/Knife.o

# target to build an object file
src/Weapons/Knife.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Weapons/Knife.cpp.o
.PHONY : src/Weapons/Knife.cpp.o

src/Weapons/Knife.i: src/Weapons/Knife.cpp.i

.PHONY : src/Weapons/Knife.i

# target to preprocess a source file
src/Weapons/Knife.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Weapons/Knife.cpp.i
.PHONY : src/Weapons/Knife.cpp.i

src/Weapons/Knife.s: src/Weapons/Knife.cpp.s

.PHONY : src/Weapons/Knife.s

# target to generate assembly for a file
src/Weapons/Knife.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Weapons/Knife.cpp.s
.PHONY : src/Weapons/Knife.cpp.s

src/Weapons/RocketLaucher.o: src/Weapons/RocketLaucher.cpp.o

.PHONY : src/Weapons/RocketLaucher.o

# target to build an object file
src/Weapons/RocketLaucher.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Weapons/RocketLaucher.cpp.o
.PHONY : src/Weapons/RocketLaucher.cpp.o

src/Weapons/RocketLaucher.i: src/Weapons/RocketLaucher.cpp.i

.PHONY : src/Weapons/RocketLaucher.i

# target to preprocess a source file
src/Weapons/RocketLaucher.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Weapons/RocketLaucher.cpp.i
.PHONY : src/Weapons/RocketLaucher.cpp.i

src/Weapons/RocketLaucher.s: src/Weapons/RocketLaucher.cpp.s

.PHONY : src/Weapons/RocketLaucher.s

# target to generate assembly for a file
src/Weapons/RocketLaucher.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Weapons/RocketLaucher.cpp.s
.PHONY : src/Weapons/RocketLaucher.cpp.s

src/Weapons/Teleport.o: src/Weapons/Teleport.cpp.o

.PHONY : src/Weapons/Teleport.o

# target to build an object file
src/Weapons/Teleport.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Weapons/Teleport.cpp.o
.PHONY : src/Weapons/Teleport.cpp.o

src/Weapons/Teleport.i: src/Weapons/Teleport.cpp.i

.PHONY : src/Weapons/Teleport.i

# target to preprocess a source file
src/Weapons/Teleport.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Weapons/Teleport.cpp.i
.PHONY : src/Weapons/Teleport.cpp.i

src/Weapons/Teleport.s: src/Weapons/Teleport.cpp.s

.PHONY : src/Weapons/Teleport.s

# target to generate assembly for a file
src/Weapons/Teleport.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/Weapons/Teleport.cpp.s
.PHONY : src/Weapons/Teleport.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/objects/Barrel.o: src/objects/Barrel.cpp.o

.PHONY : src/objects/Barrel.o

# target to build an object file
src/objects/Barrel.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/objects/Barrel.cpp.o
.PHONY : src/objects/Barrel.cpp.o

src/objects/Barrel.i: src/objects/Barrel.cpp.i

.PHONY : src/objects/Barrel.i

# target to preprocess a source file
src/objects/Barrel.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/objects/Barrel.cpp.i
.PHONY : src/objects/Barrel.cpp.i

src/objects/Barrel.s: src/objects/Barrel.cpp.s

.PHONY : src/objects/Barrel.s

# target to generate assembly for a file
src/objects/Barrel.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/objects/Barrel.cpp.s
.PHONY : src/objects/Barrel.cpp.s

src/objects/Bullet.o: src/objects/Bullet.cpp.o

.PHONY : src/objects/Bullet.o

# target to build an object file
src/objects/Bullet.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/objects/Bullet.cpp.o
.PHONY : src/objects/Bullet.cpp.o

src/objects/Bullet.i: src/objects/Bullet.cpp.i

.PHONY : src/objects/Bullet.i

# target to preprocess a source file
src/objects/Bullet.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/objects/Bullet.cpp.i
.PHONY : src/objects/Bullet.cpp.i

src/objects/Bullet.s: src/objects/Bullet.cpp.s

.PHONY : src/objects/Bullet.s

# target to generate assembly for a file
src/objects/Bullet.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/objects/Bullet.cpp.s
.PHONY : src/objects/Bullet.cpp.s

src/objects/RealisticWater.o: src/objects/RealisticWater.cpp.o

.PHONY : src/objects/RealisticWater.o

# target to build an object file
src/objects/RealisticWater.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/objects/RealisticWater.cpp.o
.PHONY : src/objects/RealisticWater.cpp.o

src/objects/RealisticWater.i: src/objects/RealisticWater.cpp.i

.PHONY : src/objects/RealisticWater.i

# target to preprocess a source file
src/objects/RealisticWater.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/objects/RealisticWater.cpp.i
.PHONY : src/objects/RealisticWater.cpp.i

src/objects/RealisticWater.s: src/objects/RealisticWater.cpp.s

.PHONY : src/objects/RealisticWater.s

# target to generate assembly for a file
src/objects/RealisticWater.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/objects/RealisticWater.cpp.s
.PHONY : src/objects/RealisticWater.cpp.s

src/objects/Tree.o: src/objects/Tree.cpp.o

.PHONY : src/objects/Tree.o

# target to build an object file
src/objects/Tree.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/objects/Tree.cpp.o
.PHONY : src/objects/Tree.cpp.o

src/objects/Tree.i: src/objects/Tree.cpp.i

.PHONY : src/objects/Tree.i

# target to preprocess a source file
src/objects/Tree.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/objects/Tree.cpp.i
.PHONY : src/objects/Tree.cpp.i

src/objects/Tree.s: src/objects/Tree.cpp.s

.PHONY : src/objects/Tree.s

# target to generate assembly for a file
src/objects/Tree.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/objects/Tree.cpp.s
.PHONY : src/objects/Tree.cpp.s

src/objects/Water.o: src/objects/Water.cpp.o

.PHONY : src/objects/Water.o

# target to build an object file
src/objects/Water.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/objects/Water.cpp.o
.PHONY : src/objects/Water.cpp.o

src/objects/Water.i: src/objects/Water.cpp.i

.PHONY : src/objects/Water.i

# target to preprocess a source file
src/objects/Water.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/objects/Water.cpp.i
.PHONY : src/objects/Water.cpp.i

src/objects/Water.s: src/objects/Water.cpp.s

.PHONY : src/objects/Water.s

# target to generate assembly for a file
src/objects/Water.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/objects/Water.cpp.s
.PHONY : src/objects/Water.cpp.s

src/scenes/Intro.o: src/scenes/Intro.cpp.o

.PHONY : src/scenes/Intro.o

# target to build an object file
src/scenes/Intro.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Intro.cpp.o
.PHONY : src/scenes/Intro.cpp.o

src/scenes/Intro.i: src/scenes/Intro.cpp.i

.PHONY : src/scenes/Intro.i

# target to preprocess a source file
src/scenes/Intro.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Intro.cpp.i
.PHONY : src/scenes/Intro.cpp.i

src/scenes/Intro.s: src/scenes/Intro.cpp.s

.PHONY : src/scenes/Intro.s

# target to generate assembly for a file
src/scenes/Intro.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Intro.cpp.s
.PHONY : src/scenes/Intro.cpp.s

src/scenes/Launcher.o: src/scenes/Launcher.cpp.o

.PHONY : src/scenes/Launcher.o

# target to build an object file
src/scenes/Launcher.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Launcher.cpp.o
.PHONY : src/scenes/Launcher.cpp.o

src/scenes/Launcher.i: src/scenes/Launcher.cpp.i

.PHONY : src/scenes/Launcher.i

# target to preprocess a source file
src/scenes/Launcher.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Launcher.cpp.i
.PHONY : src/scenes/Launcher.cpp.i

src/scenes/Launcher.s: src/scenes/Launcher.cpp.s

.PHONY : src/scenes/Launcher.s

# target to generate assembly for a file
src/scenes/Launcher.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Launcher.cpp.s
.PHONY : src/scenes/Launcher.cpp.s

src/scenes/Loose.o: src/scenes/Loose.cpp.o

.PHONY : src/scenes/Loose.o

# target to build an object file
src/scenes/Loose.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Loose.cpp.o
.PHONY : src/scenes/Loose.cpp.o

src/scenes/Loose.i: src/scenes/Loose.cpp.i

.PHONY : src/scenes/Loose.i

# target to preprocess a source file
src/scenes/Loose.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Loose.cpp.i
.PHONY : src/scenes/Loose.cpp.i

src/scenes/Loose.s: src/scenes/Loose.cpp.s

.PHONY : src/scenes/Loose.s

# target to generate assembly for a file
src/scenes/Loose.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Loose.cpp.s
.PHONY : src/scenes/Loose.cpp.s

src/scenes/Menu.o: src/scenes/Menu.cpp.o

.PHONY : src/scenes/Menu.o

# target to build an object file
src/scenes/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Menu.cpp.o
.PHONY : src/scenes/Menu.cpp.o

src/scenes/Menu.i: src/scenes/Menu.cpp.i

.PHONY : src/scenes/Menu.i

# target to preprocess a source file
src/scenes/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Menu.cpp.i
.PHONY : src/scenes/Menu.cpp.i

src/scenes/Menu.s: src/scenes/Menu.cpp.s

.PHONY : src/scenes/Menu.s

# target to generate assembly for a file
src/scenes/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Menu.cpp.s
.PHONY : src/scenes/Menu.cpp.s

src/scenes/Pause.o: src/scenes/Pause.cpp.o

.PHONY : src/scenes/Pause.o

# target to build an object file
src/scenes/Pause.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Pause.cpp.o
.PHONY : src/scenes/Pause.cpp.o

src/scenes/Pause.i: src/scenes/Pause.cpp.i

.PHONY : src/scenes/Pause.i

# target to preprocess a source file
src/scenes/Pause.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Pause.cpp.i
.PHONY : src/scenes/Pause.cpp.i

src/scenes/Pause.s: src/scenes/Pause.cpp.s

.PHONY : src/scenes/Pause.s

# target to generate assembly for a file
src/scenes/Pause.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Pause.cpp.s
.PHONY : src/scenes/Pause.cpp.s

src/scenes/Play.o: src/scenes/Play.cpp.o

.PHONY : src/scenes/Play.o

# target to build an object file
src/scenes/Play.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Play.cpp.o
.PHONY : src/scenes/Play.cpp.o

src/scenes/Play.i: src/scenes/Play.cpp.i

.PHONY : src/scenes/Play.i

# target to preprocess a source file
src/scenes/Play.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Play.cpp.i
.PHONY : src/scenes/Play.cpp.i

src/scenes/Play.s: src/scenes/Play.cpp.s

.PHONY : src/scenes/Play.s

# target to generate assembly for a file
src/scenes/Play.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Play.cpp.s
.PHONY : src/scenes/Play.cpp.s

src/scenes/Save.o: src/scenes/Save.cpp.o

.PHONY : src/scenes/Save.o

# target to build an object file
src/scenes/Save.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Save.cpp.o
.PHONY : src/scenes/Save.cpp.o

src/scenes/Save.i: src/scenes/Save.cpp.i

.PHONY : src/scenes/Save.i

# target to preprocess a source file
src/scenes/Save.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Save.cpp.i
.PHONY : src/scenes/Save.cpp.i

src/scenes/Save.s: src/scenes/Save.cpp.s

.PHONY : src/scenes/Save.s

# target to generate assembly for a file
src/scenes/Save.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Save.cpp.s
.PHONY : src/scenes/Save.cpp.s

src/scenes/Settings.o: src/scenes/Settings.cpp.o

.PHONY : src/scenes/Settings.o

# target to build an object file
src/scenes/Settings.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Settings.cpp.o
.PHONY : src/scenes/Settings.cpp.o

src/scenes/Settings.i: src/scenes/Settings.cpp.i

.PHONY : src/scenes/Settings.i

# target to preprocess a source file
src/scenes/Settings.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Settings.cpp.i
.PHONY : src/scenes/Settings.cpp.i

src/scenes/Settings.s: src/scenes/Settings.cpp.s

.PHONY : src/scenes/Settings.s

# target to generate assembly for a file
src/scenes/Settings.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Settings.cpp.s
.PHONY : src/scenes/Settings.cpp.s

src/scenes/Win.o: src/scenes/Win.cpp.o

.PHONY : src/scenes/Win.o

# target to build an object file
src/scenes/Win.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Win.cpp.o
.PHONY : src/scenes/Win.cpp.o

src/scenes/Win.i: src/scenes/Win.cpp.i

.PHONY : src/scenes/Win.i

# target to preprocess a source file
src/scenes/Win.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Win.cpp.i
.PHONY : src/scenes/Win.cpp.i

src/scenes/Win.s: src/scenes/Win.cpp.s

.PHONY : src/scenes/Win.s

# target to generate assembly for a file
src/scenes/Win.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/scenes/Win.cpp.s
.PHONY : src/scenes/Win.cpp.s

src/xmlwriter.o: src/xmlwriter.cpp.o

.PHONY : src/xmlwriter.o

# target to build an object file
src/xmlwriter.cpp.o:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/xmlwriter.cpp.o
.PHONY : src/xmlwriter.cpp.o

src/xmlwriter.i: src/xmlwriter.cpp.i

.PHONY : src/xmlwriter.i

# target to preprocess a source file
src/xmlwriter.cpp.i:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/xmlwriter.cpp.i
.PHONY : src/xmlwriter.cpp.i

src/xmlwriter.s: src/xmlwriter.cpp.s

.PHONY : src/xmlwriter.s

# target to generate assembly for a file
src/xmlwriter.cpp.s:
	$(MAKE) -f CMakeFiles/indie_studio.dir/build.make CMakeFiles/indie_studio.dir/src/xmlwriter.cpp.s
.PHONY : src/xmlwriter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... indie_studio"
	@echo "... src/Clock.o"
	@echo "... src/Clock.i"
	@echo "... src/Clock.s"
	@echo "... src/Event.o"
	@echo "... src/Event.i"
	@echo "... src/Event.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/GraphicalEngine.o"
	@echo "... src/GraphicalEngine.i"
	@echo "... src/GraphicalEngine.s"
	@echo "... src/Human.o"
	@echo "... src/Human.i"
	@echo "... src/Human.s"
	@echo "... src/IAPlayer.o"
	@echo "... src/IAPlayer.i"
	@echo "... src/IAPlayer.s"
	@echo "... src/Map.o"
	@echo "... src/Map.i"
	@echo "... src/Map.s"
	@echo "... src/Physics.o"
	@echo "... src/Physics.i"
	@echo "... src/Physics.s"
	@echo "... src/SoundEngine.o"
	@echo "... src/SoundEngine.i"
	@echo "... src/SoundEngine.s"
	@echo "... src/Weapons/AWeapon.o"
	@echo "... src/Weapons/AWeapon.i"
	@echo "... src/Weapons/AWeapon.s"
	@echo "... src/Weapons/Gun.o"
	@echo "... src/Weapons/Gun.i"
	@echo "... src/Weapons/Gun.s"
	@echo "... src/Weapons/Kamikaze.o"
	@echo "... src/Weapons/Kamikaze.i"
	@echo "... src/Weapons/Kamikaze.s"
	@echo "... src/Weapons/Knife.o"
	@echo "... src/Weapons/Knife.i"
	@echo "... src/Weapons/Knife.s"
	@echo "... src/Weapons/RocketLaucher.o"
	@echo "... src/Weapons/RocketLaucher.i"
	@echo "... src/Weapons/RocketLaucher.s"
	@echo "... src/Weapons/Teleport.o"
	@echo "... src/Weapons/Teleport.i"
	@echo "... src/Weapons/Teleport.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/objects/Barrel.o"
	@echo "... src/objects/Barrel.i"
	@echo "... src/objects/Barrel.s"
	@echo "... src/objects/Bullet.o"
	@echo "... src/objects/Bullet.i"
	@echo "... src/objects/Bullet.s"
	@echo "... src/objects/RealisticWater.o"
	@echo "... src/objects/RealisticWater.i"
	@echo "... src/objects/RealisticWater.s"
	@echo "... src/objects/Tree.o"
	@echo "... src/objects/Tree.i"
	@echo "... src/objects/Tree.s"
	@echo "... src/objects/Water.o"
	@echo "... src/objects/Water.i"
	@echo "... src/objects/Water.s"
	@echo "... src/scenes/Intro.o"
	@echo "... src/scenes/Intro.i"
	@echo "... src/scenes/Intro.s"
	@echo "... src/scenes/Launcher.o"
	@echo "... src/scenes/Launcher.i"
	@echo "... src/scenes/Launcher.s"
	@echo "... src/scenes/Loose.o"
	@echo "... src/scenes/Loose.i"
	@echo "... src/scenes/Loose.s"
	@echo "... src/scenes/Menu.o"
	@echo "... src/scenes/Menu.i"
	@echo "... src/scenes/Menu.s"
	@echo "... src/scenes/Pause.o"
	@echo "... src/scenes/Pause.i"
	@echo "... src/scenes/Pause.s"
	@echo "... src/scenes/Play.o"
	@echo "... src/scenes/Play.i"
	@echo "... src/scenes/Play.s"
	@echo "... src/scenes/Save.o"
	@echo "... src/scenes/Save.i"
	@echo "... src/scenes/Save.s"
	@echo "... src/scenes/Settings.o"
	@echo "... src/scenes/Settings.i"
	@echo "... src/scenes/Settings.s"
	@echo "... src/scenes/Win.o"
	@echo "... src/scenes/Win.i"
	@echo "... src/scenes/Win.s"
	@echo "... src/xmlwriter.o"
	@echo "... src/xmlwriter.i"
	@echo "... src/xmlwriter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

