//
// define_key.hpp for define_key in /home/fumery_h/fumery_h/rendu/tek2/cpp_indie_studio
//
// Made by
// Login   <fumery_h@epitech.net>
//
// Started on  Sat Jun 17 19:44:10 2017
// Last update Wed Jun 28 00:38:55 2017 louis
//

#ifndef		_DEFINE_KEY_
#define		_DEFINE_KEY_

const std::string	name_key[153]=
  {
    "Left mouse button",
    "Right mouse button",
    "Control-break processing",
    "Middle mouse button",
    "X1 mouse button",
    "X2 mouse button",
    "BACKSPACE key",
    "TAB key",
    "CLEAR key",
    "ENTER key",
    "SHIFT key",
    "CTRL key",
    "ALT key",
    "PAUSE key",
    "CAPS LOCK key",
    "IME Kana mode",
    "IME Hanguel mode",
    "IME Hangul mode",
    "IME Junja mode",
    "IME final mode",
    "IME Hanja mode",
    "IME Kanji mode",
    "ESC key",
    "IME convert",
    "IME nonconvert",
    "IME accept",
    "IME mode change request",
    "SPACEBAR",
    "PAGE UP key",
    "PAGE DOWN key",
    "END key",
    "HOME key",
    "LEFT ARROW key",
    "UP ARROW key",
    "RIGHT ARROW key",
    "DOWN ARROW key",
    "SELECT key",
    "PRINT key",
    "EXECUTE key",
    "PRINT SCREEN key",
    "INS key",
    "DEL key",
    "HELP key",
    "0 key",
    "1 key",
    "2 key",
    "3 key",
    "4 key",
    "5 key",
    "6 key",
    "7 key",
    "8 key",
    "9 key",
    "A key",
    "B key",
    "C key",
    "D key",
    "E key",
    "F key",
    "G key",
    "H key",
    "I key",
    "J key",
    "K key",
    "L key",
    "M key",
    "N key",
    "O key",
    "P key",
    "Q key",
    "R key",
    "S key",
    "T key",
    "U key",
    "V key",
    "W key",
    "X key",
    "Y key",
    "Z key",
    "Left Windows key ",
    "Right Windows key",
    "Applications key",
    "Computer Sleep key",
    "Numeric keypad 0 key",
    "Numeric keypad 1 key",
    "Numeric keypad 2 key",
    "Numeric keypad 3 key",
    "Numeric keypad 4 key",
    "Numeric keypad 5 key",
    "Numeric keypad 6 key",
    "Numeric keypad 7 key",
    "Numeric keypad 8 key",
    "Numeric keypad 9 key",
    "Multiply key",
    "Add key",
    "Separator key",
    "Subtract key",
    "Decimal key",
    "Divide key",
    "F1 key",
    "F2 key",
    "F3 key",
    "F4 key",
    "F5 key",
    "F6 key",
    "F7 key",
    "F8 key",
    "F9 key",
    "F10 key",
    "F11 key",
    "F12 key",
    "F13 key",
    "F14 key",
    "F15 key",
    "F16 key",
    "F17 key",
    "F18 key",
    "F19 key",
    "F20 key",
    "F21 key",
    "F22 key",
    "F23 key",
    "F24 key",
    "NUM LOCK key",
    "SCROLL LOCK key",
    "Left SHIFT key",
    "Right SHIFT key",
    "Left CONTROL key",
    "Right CONTROL key",
    "Left MENU key",
    "Right MENU key",
    "for US    \";:\"",
    "Plus Key   \"+\"",
    "Comma Key  \",\"",
    "Minus Key  \"-\"",
    "Period Key \".\"",
    "for US    \"/?\"",
    "for US    \"`~\"",
    "for US    \"[{\"",
    "for US",
    "for US",
    "for US",
    "None",
    "for Japan \"AX\"",
    "or",
    "Attn key",
    "CrSel key",
    "ExSel key",
    "Erase EOF key",
    "Play key",
    "Zoom key",
    "PA1 key",
    "Clear key",
  };

#endif		/*_DEFINE_KEY_*/
